{{- if .Values.logo }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudpbx-portal-docs.fullname" . }}-logo
  labels:
{{ include "cloudpbx-portal-docs.labels" . | indent 4 }}
binaryData:
  {{ .Values.logoFile }}: {{ .Values.logo }}
{{- end }}
